### ISSUE TITLE
Add to each polygon a centroid point

### ISSUE THREAD

**Issue by dimasciput** [unicef-drp/gis-geo-repository#43]
Add to each polygon a centroid point which has the same identifier as the polygon so that we can place pie charts / bar charts in the center of each admin area. Note there should be one point per polygon, not per tile. The point should have the UUID of the polygon for which it is the centroid as an attribute.

**Comment by timlinux** [comment]
We should calculate the centroid using the pole of inaccessibility for each polygon. Tim to share link
